#pragma once

enum Cargo { GRAIN, GENERIC_FOODS, LUXURY_FOODS, FURS, LIQUOR, PETS, WOOD, GEMS
IRON, TUNGSTEN, PLUTONIUM, URANIUM, ARTWORK, GAMES, MOVIES, ADVANCED_FUELS,
COMMUNICATIONS, COMPUTERS, CONSTRUCTION, FACTORY_EQUIPMENT, FOOD_DISPENSERS
HOLOGRAPHICS, HOME_APPLIANCES, HOME ENTERTAINMENT, MEDICAL_EQUIPMENT
MINING_EQUIPMENT, PLASTICS, PRE_FABS, ROBOT_SERVANTS, ROBOT_WORKERS,
SOFTWARE, SPACE_SALVAGE, TEXTILES, WEAPONRY, BOOKS, PLAYTHING™, BRILLIANCE,
SLAVES, TOBACCO, ULTIMATE, DATA_RECORDER }
