#pragma once

enum Faction { CONFEDERATION, KILRATHI, KILRATHI_DEFECTORS, LANDREICH, STELTEK, FIRREKKANS, RETROS, PIRATES,
		 MERCHANTS, MERCENARIES, MANDARINS, PRIVATEERS, BORDER_WORLDS, UNKNOWN };

